server:
  port: 9000

# day01：gateway 配置方式
spring:
  cloud:
    gateway:
      routes:
        - id: header_route
          uri: http://localhost:8080
          predicates:
            - Header=X-Request-Id, \d+
          filters:
            - AddRequestHeader=X-Request-red, blue
            - AddRequestParameter=color, blue









